.PHONY: clean All

All:
	@echo "----------Building project:[ P9DB_Debug - Debug ]----------"
	@"$(MAKE)" -f  "P9DB_Debug.mk"
clean:
	@echo "----------Cleaning project:[ P9DB_Debug - Debug ]----------"
	@"$(MAKE)" -f  "P9DB_Debug.mk" clean
