.PHONY: clean All

All:
	@echo "----------Building project:[ Executor - Debug ]----------"
	@"$(MAKE)" -f  "Executor.mk"
clean:
	@echo "----------Cleaning project:[ Executor - Debug ]----------"
	@"$(MAKE)" -f  "Executor.mk" clean
